### ISSUE TITLE
Unity Support

### ISSUE THREAD

**Issue by ADIX7** [Logerfo/csharp-colors#24]
In Unity you create colors with `new Color(r, g, b)` and `new Color(r, g, b, a)`, not with FromArgb.

**Comment by Logerfo** [comment]
Cool, I didn't know that. I'll try to make some time to do it soon.

For reference: https://docs.unity3d.com/ScriptReference/Color-ctor.html

**Comment by ADIX7** [comment]
Great news :D

**Comment by Logerfo** [comment]
It should be available in [0.1.4](https://github.com/Logerfo/csharp-colors/releases/tag/0.1.4).

**Comment by ADIX7** [comment]
It's working perfectly! The only missing thing is that in Unity there are predefined colors (static properties in https://docs.unity3d.com/ScriptReference/Color.html) but they are lower cased... I guess they can be simply added to colors.json. Because they are lower cased there won't be any conflict.

**Comment by Logerfo** [comment]
Yeah, probably. I'll check them out later.

**Comment by Logerfo** [comment]
Done, it should be available in [0.1.5](https://github.com/Logerfo/csharp-colors/releases/tag/0.1.5).

**Comment by ADIX7** [comment]
Thank you!
