### ISSUE TITLE
unity colors

### ISSUE THREAD

**Issue by ghiboz** [Logerfo/csharp-colors#25]
hi! it's possible use also unity colors?

![image](https://user-images.githubusercontent.com/446533/65769586-2eb9fa80-e134-11e9-8abf-6fd22188e9fe.png)

**Comment by Logerfo** [comment]
The extension already supports `new Color(r, g, b, a)` UnityEngine constructor. I don't use Unity, so I didn't know about the existence of `Color32`. They seem to be exactly the same, syntactically speaking. Am I right?

**Comment by ghiboz** [comment]
thanks @Logerfo for the fast reply:
unity uses 2 things of color constructor:
```csharp
new Color(float r, float g, float b, float a); // each color has a value from 0.0 to 1.0

new Color32(byte r, byte g, byte b, byte a); // each color has value from 0 to 255
```
hope this helps!

**Comment by Logerfo** [comment]
Should be working in 0.1.6.

**Comment by ghiboz** [comment]
sorry if I desturb you again: it has the alpha channel wrong:

![](https://i.imgur.com/Ufymape.png)

the color should be a yellowish:
https://www.color-hex.com/color/ffe700

**Comment by Logerfo** [comment]
Hmm. It's looking for `a, r, g, b`, but it should be `r, g, b, a`, right? I suppose that `new Color` should be wrong as well, then.

**Comment by ghiboz** [comment]
yes, the order is always `r, g, b, a`

**Comment by Logerfo** [comment]
It's weird that nobody ever complained about wrong unity constructions before. Anyway, it should now be working in 0.1.7.
