### ISSUE TITLE
Does not work with float parameters

### ISSUE THREAD

**Issue by convalise** [Logerfo/csharp-colors#29]
Hello.
Apparently, the extension does not work properly when using float parameters.
See the screenshot below, I have made several tests.
Using version 0.1.7

![image](https://user-images.githubusercontent.com/12805305/74451280-27368c00-4e5e-11ea-8a93-5f8c0d0992d1.png)

Thanks.

**Comment by Logerfo** [comment]
Hmm, it must be something with the regular expression, perhaps regarding the most recent changes.
Albeit not looking like it's something complex, I'm currently in a position where I have no idea when I'll be able to make time to look into this. Pull requests are very welcome, tho. Thanks for reporting it.

**Comment by Logerfo** [comment]
I'm considering the following change:
```diff
-(new\s*(?:UnityEngine\s*\.\s*)?Color\s*\()\s*\+?\s*((?:\.[0-9]?)?[0-9])[fF]\s*,\s*\+?\s*((?:\.[0-9]?)?[0-9])[fF]\s*,\s*\+?\s*((?:\.[0-9]?)?[0-9])[fF]\s*(?:,\s*\+?\s*((?:\.[0-9]?)?[0-9])[fF]\s*)?\)
+(new\s*(?:UnityEngine\s*\.\s*)?Color\s*\()\s*\+?\s*([0-9]*\.?[0-9]+)[fF]\s*,\s*\+?\s*([0-9]*\.?[0-9]+)[fF]\s*,\s*\+?\s*([0-9]*\.?[0-9]+)[fF]\s*(?:,\s*\+?\s*([0-9]*\.?[0-9]+)[fF]\s*)?\)
```
Regex 101: [Old](https://regex101.com/r/9YHM2T/2) | [New](https://regex101.com/r/E890Mg/1)
I only considered the floating point test cases, because the integer cases uses another regular expression and it seems to be working just fine according to your input.

**Comment by convalise** [comment]
The new regex matches all cases apparently, so I think it's good to go, well done.

**Comment by Logerfo** [comment]
Should be available in 0.1.8 in the next minutes.

**Comment by Logerfo** [comment]
Just a heads up: the release is not up yet because I'm having authentication problems with my extension publishing access. I'm trying to reach for support in order to work with Microsoft to fix this ASAP.

**Comment by Logerfo** [comment]
The version 0.1.8 has been now released. Sorry for the delay on this, apparently there was some inconsistencies with my account data at Microsoft side blocking me from publishing and they were only solved today.

**Comment by convalise** [comment]
I updated it today, everything seems fine :)
